logo:
  text: "我的公司"
  image: "/src/assets/images/logo.png"

navigation:
  links:
    - text: "首页"
      href: "/"
    - text: "关于"
      href: "/about"
    - text: "服务"
      href: "/services"
      links:
        - text: "网站开发"
          href: "/services/web"
        - text: "移动应用"
          href: "/services/mobile"
    - text: "博客"
      href: "/blog"
    - text: "联系"
      href: "/contact"